import { useState } from 'react';

export type PlannerLocale = 'vi' | 'en';
export const plannerCopy = {
  vi: {
    optionalNotPurchased: 'Nguyên liệu không bắt buộc không được tính vào gói mua đề xuất hoặc ngân sách.',
    quantityReview: 'Cần kiểm tra số lượng nguyên liệu', alternativesLimited: 'Đang hiển thị một phần danh mục để bạn lựa chọn.',
    rejectionNote: 'Các lý do loại trừ bên dưới thuộc về phương án đã xét, không phải kết luận lỗi của món được chọn.',
    shoppingPartial: 'Danh sách này chưa đầy đủ cho mọi nhu cầu của kế hoạch. Kiểm tra các bữa chưa xếp và các số lượng chưa rõ.',
    title: 'Bữa ngon, tuần nhẹ nhàng', eyebrow: 'TAKOSAN · THỰC ĐƠN', home: 'Trang chủ', legacy: 'Takosan Week cũ',
    week: 'Thực đơn', shopping: 'Đi chợ', newPlan: 'Lên thực đơn mới', settings: 'Điều chỉnh kế hoạch',
    intro: 'Bắt đầu từ thực phẩm bạn có. Biết rõ món sẽ nấu, thứ cần mua và điều còn chưa chắc chắn.',
    empty: 'Một tuần ngon bắt đầu từ đây', emptyText: 'Chưa có thực đơn nào cho tài khoản này. Chọn ngày và những bữa bạn muốn Takosan lên kế hoạch.',
    generate: 'Tạo thực đơn', generating: 'Takosan đang lập kế hoạch từ dữ liệu của bạn…', loading: 'Đang tải thực đơn…', retry: 'Thử lại',
    date: 'Ngày bắt đầu', days: 'Số ngày', servings: 'Số người ăn', slots: 'Bữa ăn mỗi ngày',
    breakfast: 'Bữa sáng', lunch: 'Bữa trưa', dinner: 'Bữa tối', mode: 'Nguyên liệu', allowShopping: 'Có thể mua thêm', cookNow: 'Chỉ dùng thực phẩm đang có',
    maxTime: 'Thời gian nấu tối đa (phút, không bắt buộc)', timezone: 'Dùng độ lệch múi giờ của thiết bị lúc tạo kế hoạch. Không tự điều chỉnh giờ mùa hè.',
    policy: 'Ràng buộc an toàn đã lưu trên máy chủ luôn được giữ. Cài đặt thực đơn Week cũ chưa được tự nhập sang đây.',
    invalidForm: 'Kiểm tra ngày, số người, số ngày và chọn ít nhất một bữa ăn.',
    future: 'Chỉ tạo những bữa còn ở phía trước. Hãy chọn ngày mai nếu các bữa hôm nay đã qua.',
    planNote: 'Đây là kế hoạch dự kiến, không phải thao tác trừ thực phẩm trong tủ lạnh.',
    revision: 'Phiên bản', meals: 'bữa đã chọn', details: 'Xem món', swap: 'Đổi món', regenerate: 'Lập lại thực đơn',
    regenerateTitle: 'Lập lại thực đơn này?', regenerateText: 'Takosan sẽ dùng dữ liệu hiện tại và thay toàn bộ kết quả bằng một phiên bản mới. Món đã đổi được giữ theo ràng buộc của máy chủ.',
    cancel: 'Hủy', confirm: 'Lập lại', refresh: 'Tải bản mới nhất',
    staleTitle: 'Thực đơn cần được cập nhật', staleText: 'Dữ liệu hoặc thời điểm của kế hoạch đã thay đổi. Cập nhật trước khi lập danh sách đi chợ.',
    historical: 'Kế hoạch có bữa đã qua. Tạo kế hoạch mới từ hôm nay hoặc ngày mai; thực đơn cũ vẫn được giữ. Không tự sửa các bữa đã qua.',
    updated: 'Đã tải phiên bản mới nhất. Kiểm tra lại trước khi tiếp tục.',
    unplanned: 'Bữa chưa xếp được', diagnostics: 'Vì sao có kết quả này?', limited: 'Takosan tìm thấy phương án này trong những lựa chọn đã xét. Không khẳng định đây là phương án tốt nhất có thể.',
    nutrition: 'Chưa có dữ liệu dinh dưỡng để hiển thị', safety: 'Không phải chứng nhận an toàn dị ứng. Kiểm tra nguyên liệu và các ràng buộc đã yêu cầu.',
    unknownTime: 'Chưa rõ thời gian', minutes: 'phút', people: 'người', available: 'Nguyên liệu được dự kiến từ tủ lạnh', needsShopping: 'Cần mua thêm hoặc kiểm tra số lượng',
    ingredients: 'Nguyên liệu cho bữa này', required: 'Cần', covered: 'Dự kiến từ tủ lạnh', missing: 'Cần mua thêm', optional: 'Không bắt buộc', unresolved: 'Chưa xác định được số lượng. Kiểm tra lượng thực tế trong gói hoặc đơn vị của thực phẩm.',
    instructions: 'Cách nấu', noInstructions: 'Chưa có hướng dẫn đã lưu cho món này.', reasons: 'Vì sao Takosan chọn món này?',
    explain: 'Sắp xếp lời giải thích với AI', explaining: 'Đang chuẩn bị lời giải thích…', aiNote: 'AI chỉ chọn các giải thích có căn cứ. Không thay đổi món, giá hay số lượng.', aiUsed: 'AI đã sắp xếp các lý do từ dữ liệu có sẵn.', fallback: 'Đang dùng giải thích từ dữ liệu có sẵn; không cần AI để tiếp tục.',
    chooseAlternative: 'Bạn muốn đổi sang món nào?', alternativeNote: 'Các món từ danh mục, chưa phải kết luận phù hợp. Máy chủ kiểm tra ràng buộc và lập lại toàn bộ thực đơn khi bạn chọn.',
    noAlternatives: 'Chưa có món thay thế khác trong danh mục. Bạn vẫn có thể lập lại thực đơn.', choose: 'Chọn món', swapping: 'Đang kiểm tra và lập lại thực đơn…',
    feedback: 'Bữa này thế nào?', liked: 'Thích', disliked: 'Không thích', cooked: 'Đánh dấu đã nấu', skipped: 'Bỏ qua', swapped: 'Ghi nhận đổi món',
    feedbackSaved: 'Đã ghi nhận', cookedNote: 'Chỉ đánh dấu đã nấu. Không trừ nguyên liệu, không tự đánh dấu thích.',
    shoppingIntro: 'Chỉ mua phần còn thiếu theo kế hoạch. Giá và quy cách đóng gói chưa biết luôn được ghi rõ.',
    currency: 'Tiền tệ', budget: 'Ngân sách (không bắt buộc)', budgetMode: 'Mức ngân sách', hard: 'Giới hạn bắt buộc', soft: 'Mục tiêu tham khảo',
    optimize: 'Lập danh sách đi chợ', optimizing: 'Đang kiểm tra nhu cầu và giá…', budgetInvalid: 'Nhập ngân sách không âm, đúng số chữ số thập phân của tiền tệ.',
    knownTotal: 'Chi phí đã biết', completeTotal: 'Tổng chi phí có đủ giá', unknownPrices: 'nhu cầu chưa có đủ giá', noPrices: 'Chưa có nguồn giá bán đã được duyệt. Không thể xác nhận tổng chi phí.',
    list: 'Danh sách cần mua', noShopping: 'Không có nhu cầu mua đã xác định. Kiểm tra các mục chưa rõ bên dưới nếu có.',
    priceUnavailable: 'Chưa có giá hoặc phương án mua phù hợp', selectedPackages: 'Gói đề xuất', surplus: 'Dự kiến còn lại sau kế hoạch',
    checklistNote: 'Dấu tích chỉ dùng để ghi nhớ trong lần xem này. Không đặt hàng, thanh toán hay thêm thực phẩm vào tủ lạnh.',
    largestCosts: 'Các chi phí đã biết lớn nhất', gap: 'Vượt ngân sách đã biết', bestKnown: 'Phương án tốt nhất Takosan tìm được',
    waste: 'Thực phẩm còn lại & rủi ro', wasteUnknown: 'Chưa đủ thông tin hạn dùng để đánh giá một số thực phẩm.', wasteAtRisk: 'Một số thực phẩm có thể còn lại gần hạn dùng.', wasteNone: 'Không phát hiện rủi ro có ngày cụ thể trong kỳ kế hoạch.',
    wasteNote: 'Dư sau mua không có nghĩa là chắc chắn lãng phí.', priceAsOf: 'Giá được kiểm tra lúc',
    mealUnavailable: 'Không tìm thấy bữa này trong phiên bản hiện tại.', back: 'Về thực đơn', checked: 'Đã ghi nhớ',
  },
  en: {
    optionalNotPurchased: 'Optional items are not included in suggested purchases or the budget.',
    quantityReview: 'Ingredient quantity review needed', alternativesLimited: 'Showing a limited selection from the catalog.',
    rejectionNote: 'Rejection reasons below concern evaluated alternatives, not failures of the selected meals.',
    shoppingPartial: 'This list does not cover every planning need. Review unplanned meals and unresolved quantities.',
    title: 'Good meals. A lighter week.', eyebrow: 'TAKOSAN · MEAL PLANNER', home: 'Home', legacy: 'Legacy Takosan Week',
    week: 'Meals', shopping: 'Shopping', newPlan: 'Plan a new week', settings: 'Adjust the plan',
    intro: 'Start with what you have. See what to cook, what to buy, and what is still uncertain.',
    empty: 'A delicious week starts here', emptyText: 'No plan for this account yet. Choose a start date and the meals you want Takosan to plan.',
    generate: 'Generate plan', generating: 'Takosan is planning from your data…', loading: 'Loading your plan…', retry: 'Try again',
    date: 'Start date', days: 'Number of days', servings: 'Servings', slots: 'Meals each day',
    breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner', mode: 'Ingredients', allowShopping: 'Allow shopping', cookNow: 'Use only what I have',
    maxTime: 'Maximum cooking time (minutes, optional)', timezone: 'Uses your device’s fixed UTC offset at generation. Daylight-saving changes are not inferred.',
    policy: 'Server-saved hard restrictions always apply. Legacy Week preferences are not imported automatically.',
    invalidForm: 'Check the date, servings and days, and select at least one meal.',
    future: 'Only future meals can be planned. Choose tomorrow if today’s meals have passed.',
    planNote: 'This is a projected plan, not a deduction from your real fridge.',
    revision: 'Revision', meals: 'meals selected', details: 'View meal', swap: 'Swap meal', regenerate: 'Regenerate plan',
    regenerateTitle: 'Regenerate this plan?', regenerateText: 'Takosan will use current data and replace the full result with a new revision. Previously swapped meals retain their server constraints.',
    cancel: 'Cancel', confirm: 'Regenerate', refresh: 'Refresh latest plan',
    staleTitle: 'Your plan needs an update', staleText: 'The data or timing of this plan has changed. Update it before preparing shopping.',
    historical: 'Some meals are in the past. Create a new plan starting today or tomorrow; this plan is retained. Past meals are not edited locally.',
    updated: 'The latest plan has been loaded. Review it before continuing.',
    unplanned: 'Meal not planned', diagnostics: 'About this result', limited: 'Takosan found this plan among the options evaluated. It is not a claim of the best possible plan.',
    nutrition: 'Nutrition data is not available for display', safety: 'Not an allergy-safety certification. Check ingredients and the restrictions you requested.',
    unknownTime: 'Cooking time unknown', minutes: 'min', people: 'servings', available: 'Ingredients projected from your fridge', needsShopping: 'Shopping or quantity review needed',
    ingredients: 'Ingredients for this meal', required: 'Needed', covered: 'Projected from fridge', missing: 'Still needed', optional: 'Optional', unresolved: 'Exact quantity unresolved. Check the package contents or inventory unit.',
    instructions: 'Method', noInstructions: 'No stored instructions are available for this meal.', reasons: 'Why this meal?',
    explain: 'Arrange explanation with AI', explaining: 'Preparing explanation…', aiNote: 'AI only selects grounded explanations. It cannot change meals, prices or quantities.', aiUsed: 'AI arranged these reasons from existing facts.', fallback: 'Using the structured-data explanation. You do not need AI to continue.',
    chooseAlternative: 'What would you like instead?', alternativeNote: 'Catalog choices, not eligibility claims. The server checks restrictions and replans the entire week when you select one.',
    noAlternatives: 'No other catalog choices are available. You can still regenerate the plan.', choose: 'Choose meal', swapping: 'Checking and replanning your meals…',
    feedback: 'How was this meal?', liked: 'Like', disliked: 'Dislike', cooked: 'Mark cooked', skipped: 'Skip', swapped: 'Record swap feedback',
    feedbackSaved: 'Recorded', cookedNote: 'An annotation only. No ingredients are deducted and no like is implied.',
    shoppingIntro: 'Buy only what the plan still needs. Missing prices and package information stay visible.',
    currency: 'Currency', budget: 'Budget (optional)', budgetMode: 'Budget policy', hard: 'Hard limit', soft: 'Soft target',
    optimize: 'Prepare shopping list', optimizing: 'Checking needs and prices…', budgetInvalid: 'Enter a non-negative budget using the currency’s supported decimal places.',
    knownTotal: 'Known cost', completeTotal: 'Total with complete pricing', unknownPrices: 'requirements without complete prices', noPrices: 'No reviewed retail prices are available. The final cost cannot be confirmed.',
    list: 'What to buy', noShopping: 'No known purchase demand. Check unresolved items below, if any.',
    priceUnavailable: 'Price or suitable purchase option unavailable', selectedPackages: 'Suggested packages', surplus: 'Projected remainder after this plan',
    checklistNote: 'Checks are reminders for this view only. They do not place orders, make payments or add stock to your fridge.',
    largestCosts: 'Largest known costs', gap: 'Known amount over budget', bestKnown: 'Best option Takosan found',
    waste: 'Remaining food & risk', wasteUnknown: 'Some items lack enough shelf-life information to assess risk.', wasteAtRisk: 'Some food may remain near its expiry date.', wasteNone: 'No dated risk detected within this planning horizon.',
    wasteNote: 'Purchase surplus is not certain waste.', priceAsOf: 'Prices checked at',
    mealUnavailable: 'This meal is not in the current plan revision.', back: 'Back to meals', checked: 'Checked',
  },
} as const;

export function usePlannerLocale() {
  const [locale, setLocale] = useState<PlannerLocale>(() => {
    try { return localStorage.getItem('frigo_planner_locale') === 'en' ? 'en' : 'vi'; }
    catch { return 'vi'; }
  });
  return { locale, copy: plannerCopy[locale], setLocale: (value: PlannerLocale) => {
    setLocale(value);
    try { localStorage.setItem('frigo_planner_locale', value); } catch { /* Optional presentation preference. */ }
  } };
}
