-- Migration 0034: D1 catalog parity for the current 71-recipe runtime set (T14B-B).
-- Rendered from @frigo/recipes ALL_RECIPES by renderGlobalRecipeParitySql; immutable once applied.
--
-- 1. The 12 global recipes (gl-01..gl-12) that 0006 never seeded, under their stable static IDs
--    and slugs. ON CONFLICT upgrades a 7-column FK anchor row left behind by cooking/shopping
--    into a complete entry without touching provenance columns (schema defaults
--    legacy/unverified/1 are the only truthful values available).
-- 2. recipe_runtime_fields: typed, queryable home for the runtime-only fields the foundation
--    RecipeDefinition omits (category, region) plus LEGACY nutrition compatibility macros.
--    Those macros are a compatibility projection of the static catalog, NOT nutrition_profiles
--    evidence. recipes.image_url stays LEGACY_MEDIA_COMPATIBILITY_ONLY; media authority is T14C.
-- 3. No historical migration, existing recipe row, inventory table or user data is modified.

INSERT INTO recipes (id, slug, title, description, cuisine, cook_time_minutes, servings, difficulty, image_url, tags) VALUES
('gl-01', 'pasta-pomodoro', 'Mì Ý sốt cà chua Pomodoro', 'Món mì Ý kinh điển với sốt cà chua tươi, tỏi phi thơm và dầu olive tinh tế.', 'italian', 18, 2, 'easy', '/frigo/recipes/global/pasta-pomodoro.webp', '["Ý","Pasta","Dưới 20 phút"]'),
('gl-02', 'mapo-tofu', 'Đậu phụ sốt Mapo Tofu Tứ Xuyên', 'Đậu phụ mềm non ngập trong sốt cay nồng tê tê chuẩn vị Trung Hoa.', 'chinese', 16, 3, 'medium', '/frigo/recipes/global/mapo-tofu.webp', '["Trung Hoa","Cay","Đậu phụ"]'),
('gl-03', 'tomato-egg-stir-fry', 'Cà chua xào trứng Trung Hoa', 'Món ăn gia đình kinh điển với trứng mềm xốp quyện sốt cà chua đỏ sánh mịn.', 'chinese', 10, 2, 'easy', '/frigo/recipes/global/tomato-egg-stir-fry.webp', '["Trung Hoa","Dưới 20 phút","Nhanh gọn"]'),
('gl-04', 'oyakodon', 'Cơm gà trứng Oyakodon Nhật Bản', 'Món cơm donburi Nhật Bản với thịt gà mềm ngọt và trứng nấu lướt mịn mượt trên bát cơm nóng.', 'japanese', 15, 2, 'easy', '/frigo/recipes/global/oyakodon.webp', '["Nhật Bản","Dưới 20 phút","Cơm donburi"]'),
('gl-05', 'kimchi-fried-rice', 'Cơm chiên kim chi Hàn Quốc', 'Cơm chiên kim chi chua cay giòn sần sật phủ trứng ốp la lòng đào béo ngậy.', 'korean', 15, 2, 'easy', '/frigo/recipes/global/kimchi-fried-rice.webp', '["Hàn Quốc","Dưới 20 phút","Cay"]'),
('gl-06', 'pad-krapow', 'Thịt băm xào lá quế kiểu Thái (Pad Krapow)', 'Món thịt heo băm xào cay thơm lừng lá quế ăn kèm cơm trắng và trứng rán giòn viền.', 'thai', 12, 2, 'easy', '/frigo/recipes/global/pad-krapow.webp', '["Thái Lan","Dưới 20 phút","Cay"]'),
('gl-07', 'kimbap-han-quoc', 'Cơm cuộn Kimbap Hàn Quốc', 'Cơm cuộn rong biển nhân trứng rán, xúc xích/thịt và dưa chuột giòn mát rượi.', 'korean', 20, 3, 'easy', '/frigo/recipes/global/kimchi-fried-rice.webp', '["Hàn Quốc","Meal prep","Dã ngoại"]'),
('gl-08', 'tokbokki-cay-ngot', 'Bánh gạo Tokbokki sốt cay ngọt', 'Bánh gạo dẻo mềm đượm sốt ớt Gochujang cay nồng cùng trứng luộc lòng đào.', 'korean', 18, 2, 'easy', '/frigo/recipes/global/kimchi-fried-rice.webp', '["Hàn Quốc","Món ăn vặt","Cay"]'),
('gl-09', 'chawanmushi', 'Trứng hấp Chawanmushi Nhật Bản', 'Trứng hấp mịn màng như thạch tan trong miệng cùng tôm ngọt và nấm.', 'japanese', 15, 2, 'easy', '/frigo/recipes/global/oyakodon.webp', '["Nhật Bản","Thanh đạm","Bữa tối nhẹ"]'),
('gl-10', 'thai-green-curry', 'Cà ri gà kiểu Thái (Green Curry)', 'Thịt gà mềm ngập trong nước sốt cà ri cốt dừa béo ngậy thơm nồng lá quế và ớt xanh.', 'thai', 25, 3, 'medium', '/frigo/recipes/global/pad-krapow.webp', '["Thái Lan","Béo ngậy","Cay nồng"]'),
('gl-11', 'spaghetti-bolognese', 'Mì Ý sốt bò băm Bolognese', 'Sợi mì Ý dai mềm đượm sốt cà chua thịt bò băm thơm lừng thảo mộc Ý.', 'italian', 25, 3, 'easy', '/frigo/recipes/global/carbonara.webp', '["Món Ý","Được yêu thích","Trẻ em mê"]'),
('gl-12', 'chinese-tomato-egg', 'Trứng xào cà chua kiểu Trung Hoa', 'Món ăn gia đình kinh điển Trung Hoa với trứng mềm xốp ngập trong sốt cà chua đỏ sánh chua ngọt.', 'chinese', 10, 2, 'easy', '/frigo/recipes/vietnam/dau-phu-sot-ca-chua.webp', '["Trung Hoa","Dưới 15 phút","Siêu nhanh"]')
ON CONFLICT(id) DO UPDATE SET
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  cuisine = excluded.cuisine,
  cook_time_minutes = excluded.cook_time_minutes,
  servings = excluded.servings,
  difficulty = excluded.difficulty,
  image_url = excluded.image_url,
  tags = excluded.tags;

INSERT INTO recipe_ingredients (id, recipe_id, ingredient_id, name, required_quantity, unit, is_optional) VALUES
('gl-01_ing_1', 'gl-01', 'SPAGHETTI_PASTA', 'Mì Ý', 180, 'g', 0),
('gl-01_ing_2', 'gl-01', 'TOMATO', 'Cà chua', 3, 'piece', 0),
('gl-01_ing_3', 'gl-01', 'GARLIC', 'Tỏi', 1, 'piece', 0),
('gl-01_ing_4', 'gl-01', 'COOKING_OIL', 'Dầu olive / Dầu ăn', 15, 'ml', 0),
('gl-02_ing_1', 'gl-02', 'TOFU', 'Đậu phụ', 2, 'piece', 0),
('gl-02_ing_2', 'gl-02', 'GROUND_PORK', 'Thịt heo xay', 100, 'g', 0),
('gl-02_ing_3', 'gl-02', 'GARLIC', 'Tỏi', 1, 'piece', 0),
('gl-02_ing_4', 'gl-02', 'GINGER', 'Gừng', 10, 'g', 0),
('gl-02_ing_5', 'gl-02', 'CHILI', 'Ớt', 1, 'piece', 0),
('gl-03_ing_1', 'gl-03', 'CHICKEN_EGG', 'Trứng gà', 3, 'piece', 0),
('gl-03_ing_2', 'gl-03', 'TOMATO', 'Cà chua', 2, 'piece', 0),
('gl-03_ing_3', 'gl-03', 'SCALLION', 'Hành lá', 1, 'bunch', 0),
('gl-03_ing_4', 'gl-03', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('gl-04_ing_1', 'gl-04', 'CHICKEN_THIGH', 'Thịt đùi gà', 200, 'g', 0),
('gl-04_ing_2', 'gl-04', 'CHICKEN_EGG', 'Trứng gà', 2, 'piece', 0),
('gl-04_ing_3', 'gl-04', 'ONION', 'Hành tây', 1, 'piece', 0),
('gl-04_ing_4', 'gl-04', 'SOY_SAUCE', 'Nước tương', 20, 'ml', 0),
('gl-04_ing_5', 'gl-04', 'RICE', 'Cơm', 300, 'g', 0),
('gl-05_ing_1', 'gl-05', 'RICE', 'Cơm nguội', 250, 'g', 0),
('gl-05_ing_2', 'gl-05', 'KIMCHI', 'Kim chi', 150, 'g', 0),
('gl-05_ing_3', 'gl-05', 'CHICKEN_EGG', 'Trứng gà', 1, 'piece', 0),
('gl-05_ing_4', 'gl-05', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('gl-06_ing_1', 'gl-06', 'GROUND_PORK', 'Thịt heo xay', 250, 'g', 0),
('gl-06_ing_2', 'gl-06', 'CHILI', 'Ớt', 2, 'piece', 0),
('gl-06_ing_3', 'gl-06', 'GARLIC', 'Tỏi', 1, 'piece', 0),
('gl-06_ing_4', 'gl-06', 'FISH_SAUCE', 'Nước mắm', 15, 'ml', 0),
('gl-06_ing_5', 'gl-06', 'CHICKEN_EGG', 'Trứng gà', 1, 'piece', 0),
('gl-07_ing_1', 'gl-07', 'RICE', 'Cơm trắng', 300, 'g', 0),
('gl-07_ing_2', 'gl-07', 'CHICKEN_EGG', 'Trứng gà', 3, 'piece', 0),
('gl-07_ing_3', 'gl-07', 'CARROT', 'Cà rốt', 1, 'piece', 0),
('gl-07_ing_4', 'gl-07', 'CUCUMBER', 'Dưa leo', 1, 'piece', 0),
('gl-07_ing_5', 'gl-07', 'COOKING_OIL', 'Dầu ăn', 10, 'ml', 0),
('gl-08_ing_1', 'gl-08', 'RICE', 'Bánh gạo / Bột gạo', 250, 'g', 0),
('gl-08_ing_2', 'gl-08', 'CHICKEN_EGG', 'Trứng gà', 2, 'piece', 0),
('gl-08_ing_3', 'gl-08', 'CABBAGE', 'Bắp cải', 1, 'piece', 0),
('gl-08_ing_4', 'gl-08', 'SCALLION', 'Hành lá', 1, 'bunch', 0),
('gl-08_ing_5', 'gl-08', 'CHILI', 'Ớt bột / Tương ớt', 2, 'piece', 0),
('gl-09_ing_1', 'gl-09', 'CHICKEN_EGG', 'Trứng gà', 2, 'piece', 0),
('gl-09_ing_2', 'gl-09', 'SHRIMP', 'Tôm tươi', 100, 'g', 0),
('gl-09_ing_3', 'gl-09', 'SOY_SAUCE', 'Nước tương Nhật', 10, 'ml', 0),
('gl-09_ing_4', 'gl-09', 'SCALLION', 'Hành lá', 1, 'bunch', 1),
('gl-10_ing_1', 'gl-10', 'CHICKEN_THIGH', 'Thịt đùi gà', 400, 'g', 0),
('gl-10_ing_2', 'gl-10', 'FRESH_MILK', 'Sữa tươi/Cốt dừa', 200, 'ml', 0),
('gl-10_ing_3', 'gl-10', 'CHILI', 'Ớt xanh/đỏ', 2, 'piece', 0),
('gl-10_ing_4', 'gl-10', 'GARLIC', 'Tỏi', 1, 'piece', 0),
('gl-10_ing_5', 'gl-10', 'FISH_SAUCE', 'Nước mắm', 20, 'ml', 0),
('gl-11_ing_1', 'gl-11', 'SPAGHETTI_PASTA', 'Mì Ý Spaghetti', 250, 'g', 0),
('gl-11_ing_2', 'gl-11', 'GROUND_PORK', 'Thịt bò/heo băm', 300, 'g', 0),
('gl-11_ing_3', 'gl-11', 'TOMATO', 'Cà chua', 4, 'piece', 0),
('gl-11_ing_4', 'gl-11', 'ONION', 'Hành tây', 1, 'piece', 0),
('gl-11_ing_5', 'gl-11', 'GARLIC', 'Tỏi', 1, 'piece', 0),
('gl-11_ing_6', 'gl-11', 'COOKING_OIL', 'Dầu ô liu', 15, 'ml', 0),
('gl-12_ing_1', 'gl-12', 'CHICKEN_EGG', 'Trứng gà', 3, 'piece', 0),
('gl-12_ing_2', 'gl-12', 'TOMATO', 'Cà chua', 3, 'piece', 0),
('gl-12_ing_3', 'gl-12', 'SCALLION', 'Hành lá', 1, 'bunch', 0),
('gl-12_ing_4', 'gl-12', 'COOKING_OIL', 'Dầu ăn', 15, 'ml', 0),
('gl-12_ing_5', 'gl-12', 'SOY_SAUCE', 'Nước tương', 10, 'ml', 0)
ON CONFLICT(id) DO UPDATE SET
  recipe_id = excluded.recipe_id,
  ingredient_id = excluded.ingredient_id,
  name = excluded.name,
  required_quantity = excluded.required_quantity,
  unit = excluded.unit,
  is_optional = excluded.is_optional;

INSERT INTO recipe_steps (id, recipe_id, step_number, instruction, tip, timer_minutes) VALUES
('gl-01_step_1', 'gl-01', 1, 'Luộc mì Ý trong nước sôi có chút muối trong 8 phút chín al dente.', NULL, 8),
('gl-01_step_2', 'gl-01', 2, 'Phi thơm tỏi băm trong dầu olive trên lửa nhỏ.', NULL, NULL),
('gl-01_step_3', 'gl-01', 3, 'Thêm cà chua băm nhuyễn, đun nhỏ lửa 6 phút tạo sốt sánh mịn.', NULL, NULL),
('gl-01_step_4', 'gl-01', 4, 'Trộn mì vào sốt, rắc tiêu và phô mai lên trên.', NULL, NULL),
('gl-02_step_1', 'gl-02', 1, 'Đậu phụ cắt hạt lựu, chần qua nước sôi 1 phút.', NULL, NULL),
('gl-02_step_2', 'gl-02', 2, 'Phi tỏi, gừng và ớt băm, xào chín thịt băm.', NULL, NULL),
('gl-02_step_3', 'gl-02', 3, 'Thêm gia vị cay và 1/2 chén nước đun sôi, thả đậu phụ vào rim 5 phút.', NULL, NULL),
('gl-03_step_1', 'gl-03', 1, 'Đánh tan trứng với chút muối. Cà chua cắt múi cau.', NULL, NULL),
('gl-03_step_2', 'gl-03', 2, 'Chiên trứng xốp mềm rồi gắp ra đĩa.', NULL, NULL),
('gl-03_step_3', 'gl-03', 3, 'Xào cà chua ra nước sốt đỏ sánh cùng chút muối.', NULL, NULL),
('gl-03_step_4', 'gl-03', 4, 'Trút trứng vào đảo nhanh tay 30 giây rồi tắt bếp.', NULL, NULL),
('gl-04_step_1', 'gl-04', 1, 'Gà cắt miếng vừa ăn, hành tây thái mỏng.', NULL, NULL),
('gl-04_step_2', 'gl-04', 2, 'Đun sôi nước tương, đường và chút nước, thả gà hành tây vào nấu 5 phút.', NULL, NULL),
('gl-04_step_3', 'gl-04', 3, 'Rưới trứng đánh nhẹ lên trên đậy vung 1 phút chín lòng đào rồi trút lên bát cơm.', NULL, NULL),
('gl-05_step_1', 'gl-05', 1, 'Kim chi vắt nhẹ bớt nước, băm nhỏ.', NULL, NULL),
('gl-05_step_2', 'gl-05', 2, 'Xào kim chi thơm với dầu ăn 2 phút.', NULL, NULL),
('gl-05_step_3', 'gl-05', 3, 'Cho cơm nguội vào đảo đều tay trên lửa lớn cho hạt săn tơi.', NULL, NULL),
('gl-05_step_4', 'gl-05', 4, 'Chiên 1 trứng ốp la lòng đào đặt lên bát cơm thưởng thức.', NULL, NULL),
('gl-06_step_1', 'gl-06', 1, 'Phi thơm tỏi ớt băm trên lửa lớn.', NULL, NULL),
('gl-06_step_2', 'gl-06', 2, 'Cho thịt băm vào xào săn tơi đều 3 phút.', NULL, NULL),
('gl-06_step_3', 'gl-06', 3, 'Nêm nước mắm hạt nêm, cho lá quế/húng quế vào đảo nhanh tắt bếp.', NULL, NULL),
('gl-06_step_4', 'gl-06', 4, 'Chiên ốp la 1 quả trứng lòng đào ăn kèm.', NULL, NULL),
('gl-07_step_1', 'gl-07', 1, 'Trộn cơm với chút dầu mè và muối cho đậm đà.', NULL, NULL),
('gl-07_step_2', 'gl-07', 2, 'Tráng trứng mỏng rồi cắt sợi dài, cà rốt và dưa leo cắt sợi dài.', NULL, NULL),
('gl-07_step_3', 'gl-07', 3, 'Trải lá rong biển, dàn đều cơm rồi xếp nhân trứng, cà rốt, dưa leo.', NULL, NULL),
('gl-07_step_4', 'gl-07', 4, 'Cuộn chặt tay rồi cắt thành từng khoanh tròn 1.5cm.', NULL, NULL),
('gl-08_step_1', 'gl-08', 1, 'Luộc 2 quả trứng gà bóc vỏ để sẵn.', NULL, 7),
('gl-08_step_2', 'gl-08', 2, 'Đun sôi nước với tương ớt Hàn Quốc, đường và nước tương.', NULL, NULL),
('gl-08_step_3', 'gl-08', 3, 'Cho bánh gạo và bắp cải vào đảo đều đun nhỏ lửa 8 phút cho ngấm sốt.', NULL, 8),
('gl-08_step_4', 'gl-08', 4, 'Thêm trứng luộc và hành lá, đun đến khi sốt sánh sệt đỏ au.', NULL, NULL),
('gl-09_step_1', 'gl-09', 1, 'Đánh tan 2 quả trứng với 200ml nước dùng dashi/nước lọc và xì dầu.', NULL, NULL),
('gl-09_step_2', 'gl-09', 2, 'Lọc hỗn hợp qua rây mịn 2 lần để mặt trứng không bị rỗ bọt khí.', NULL, NULL),
('gl-09_step_3', 'gl-09', 3, 'Xếp tôm vào chén, rót hỗn hợp trứng vào đậy nắp chén lại.', NULL, NULL),
('gl-09_step_4', 'gl-09', 4, 'Hấp cách thủy trên lửa cực nhỏ trong 10 phút cho trứng đông mượt.', NULL, 10),
('gl-10_step_1', 'gl-10', 1, 'Thịt gà chặt miếng vừa ăn, phi thơm tỏi băm và bột cà ri.', NULL, NULL),
('gl-10_step_2', 'gl-10', 2, 'Cho thịt gà vào xào săn trên lửa vừa 4 phút.', NULL, NULL),
('gl-10_step_3', 'gl-10', 3, 'Đổ sữa tươi/cốt dừa và 100ml nước vào đun sôi nhỏ lửa 15 phút.', NULL, 15),
('gl-10_step_4', 'gl-10', 4, 'Nêm nước mắm đường, cho ớt và lá húng quế vào rồi tắt bếp.', NULL, NULL),
('gl-11_step_1', 'gl-11', 1, 'Luộc mì Ý trong nước sôi có muối trong 9 phút đến khi chín tới (al dente).', NULL, 9),
('gl-11_step_2', 'gl-11', 2, 'Phi thơm tỏi và hành tây băm nhỏ trên chảo dầu ô liu.', NULL, NULL),
('gl-11_step_3', 'gl-11', 3, 'Cho thịt băm vào xào tơi, tiếp tục cho cà chua băm nhuyễn vào đun liu riu 12 phút.', NULL, 12),
('gl-11_step_4', 'gl-11', 4, 'Gắp mì ra đĩa, chan ngập sốt bò băm nóng hổi lên trên thưởng thức.', NULL, NULL),
('gl-12_step_1', 'gl-12', 1, 'Đánh tan 3 quả trứng với xíu muối. Rán trứng trên chảo dầu nóng vừa chín tới thì dầm miếng to trút ra đĩa.', NULL, NULL),
('gl-12_step_2', 'gl-12', 2, 'Cà chua cắt múi cau, xào mềm tiết nước sốt đỏ sánh trong 3 phút.', NULL, NULL),
('gl-12_step_3', 'gl-12', 3, 'Đổ trứng rán vào chảo cà chua, nêm chút đường xì dầu đảo nhẹ tay 1 phút.', NULL, NULL),
('gl-12_step_4', 'gl-12', 4, 'Rắc hành hoa cắt nhỏ, tắt bếp múc ra đĩa ăn nóng với cơm.', NULL, NULL)
ON CONFLICT(id) DO UPDATE SET
  recipe_id = excluded.recipe_id,
  step_number = excluded.step_number,
  instruction = excluded.instruction,
  tip = excluded.tip,
  timer_minutes = excluded.timer_minutes;

CREATE TABLE IF NOT EXISTS recipe_runtime_fields (
  recipe_id TEXT PRIMARY KEY NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  category TEXT CHECK (category IS NULL OR length(trim(category)) > 0),
  region TEXT CHECK (region IS NULL OR region IN ('bac', 'trung', 'nam', 'toan_quoc')),
  legacy_calories REAL CHECK (legacy_calories IS NULL OR (legacy_calories >= 0 AND legacy_calories < 1e308)),
  legacy_protein_g REAL CHECK (legacy_protein_g IS NULL OR (legacy_protein_g >= 0 AND legacy_protein_g < 1e308)),
  legacy_fat_g REAL CHECK (legacy_fat_g IS NULL OR (legacy_fat_g >= 0 AND legacy_fat_g < 1e308)),
  legacy_carb_g REAL CHECK (legacy_carb_g IS NULL OR (legacy_carb_g >= 0 AND legacy_carb_g < 1e308)),
  CHECK (
    (legacy_calories IS NULL AND legacy_protein_g IS NULL AND legacy_fat_g IS NULL AND legacy_carb_g IS NULL) OR
    (legacy_calories IS NOT NULL AND legacy_protein_g IS NOT NULL AND legacy_fat_g IS NOT NULL AND legacy_carb_g IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS idx_recipe_runtime_fields_category ON recipe_runtime_fields(category, recipe_id) WHERE category IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_recipe_runtime_fields_region ON recipe_runtime_fields(region, recipe_id) WHERE region IS NOT NULL;

INSERT INTO recipe_runtime_fields (recipe_id, category, region, legacy_calories, legacy_protein_g, legacy_fat_g, legacy_carb_g) VALUES
('vn-canh-01', 'mon_canh', 'nam', 285, 26, 7, 28),
('vn-canh-02', 'mon_canh', 'bac', 195, 22, 5, 14),
('vn-canh-03', 'mon_canh', 'nam', 230, 21, 9, 15),
('vn-canh-04', 'mon_canh', 'toan_quoc', 310, 25, 16, 12),
('vn-canh-05', 'mon_canh', 'toan_quoc', 215, 18, 7, 22),
('vn-canh-06', 'mon_canh', 'bac', 160, 19, 4, 13),
('vn-kho-01', 'mon_kho', 'nam', 480, 32, 34, 10),
('vn-kho-02', 'mon_kho', 'nam', 340, 35, 14, 16),
('vn-kho-03', 'mon_kho', 'toan_quoc', 370, 34, 20, 8),
('vn-kho-04', 'mon_kho', 'bac', 420, 28, 25, 22),
('vn-kho-05', 'mon_kho', 'toan_quoc', 240, 29, 8, 14),
('vn-kho-06', 'mon_kho', 'bac', 390, 24, 28, 12),
('vn-xao-01', 'mon_xao', 'toan_quoc', 120, 4, 7, 9),
('vn-xao-02', 'mon_xao', 'bac', 290, 28, 12, 14),
('vn-xao-03', 'mon_xao', 'toan_quoc', 220, 27, 6, 15),
('vn-xao-04', 'mon_xao', 'toan_quoc', 260, 26, 11, 16),
('vn-xao-05', 'mon_xao', 'bac', 180, 11, 10, 12),
('vn-xao-06', 'mon_xao', 'toan_quoc', 250, 25, 10, 14),
('vn-chien-01', 'mon_chien', 'toan_quoc', 230, 17, 13, 12),
('vn-chien-02', 'mon_chien', 'toan_quoc', 270, 22, 19, 5),
('vn-chien-03', 'mon_chien', 'toan_quoc', 430, 31, 28, 14),
('vn-chien-04', 'mon_chien', 'bac', 310, 32, 16, 8),
('vn-chien-05', 'mon_chien', 'bac', 380, 22, 22, 26),
('vn-chien-06', 'mon_chien', 'toan_quoc', 330, 34, 18, 4),
('vn-hap-01', 'mon_hap_luoc', 'bac', 340, 38, 18, 2),
('vn-hap-02', 'mon_hap_luoc', 'bac', 360, 25, 28, 2),
('vn-hap-03', 'mon_hap_luoc', 'toan_quoc', 290, 36, 10, 8),
('vn-hap-04', 'mon_hap_luoc', 'nam', 250, 14, 15, 18),
('vn-hap-05', 'mon_hap_luoc', 'trung', 175, 31, 3, 4),
('vn-hap-06', 'mon_hap_luoc', 'nam', 190, 30, 3, 8),
('vn-cuon-01', 'mon_cuon_nom', 'nam', 310, 22, 8, 38),
('vn-cuon-02', 'mon_cuon_nom', 'bac', 330, 24, 9, 40),
('vn-cuon-03', 'mon_cuon_nom', 'bac', 260, 20, 12, 18),
('vn-cuon-04', 'mon_cuon_nom', 'trung', 280, 32, 10, 16),
('vn-cuon-05', 'mon_cuon_nom', 'bac', 210, 16, 5, 26),
('vn-cuon-06', 'mon_cuon_nom', 'trung', 370, 25, 20, 22),
('vn-bun-01', 'mon_bun_pho', 'bac', 480, 34, 14, 56),
('vn-bun-02', 'mon_bun_pho', 'bac', 510, 32, 24, 45),
('vn-bun-03', 'mon_bun_pho', 'trung', 530, 36, 22, 50),
('vn-bun-04', 'mon_bun_pho', 'bac', 440, 30, 16, 48),
('vn-bun-05', 'mon_bun_pho', 'nam', 490, 28, 20, 52),
('vn-bun-06', 'mon_bun_pho', 'bac', 360, 29, 8, 45),
('vn-chay-01', 'mon_chay', 'toan_quoc', 210, 18, 9, 16),
('vn-chay-02', 'mon_chay', 'toan_quoc', 170, 8, 3, 28),
('vn-chay-03', 'mon_chay', 'toan_quoc', 310, 12, 11, 42),
('vn-chay-04', 'mon_chay', 'nam', 160, 4, 11, 14),
('vn-chay-05', 'mon_chay', 'toan_quoc', 180, 14, 7, 16),
('vn-chay-06', 'mon_chay', 'toan_quoc', 125, 10, 5, 11),
('vn-sang-01', 'mon_nhanh_sang', 'toan_quoc', 380, 14, 12, 55),
('vn-sang-02', 'mon_nhanh_sang', 'toan_quoc', 420, 19, 22, 38),
('vn-sang-03', 'mon_nhanh_sang', 'toan_quoc', 290, 20, 8, 35),
('vn-sang-04', 'mon_nhanh_sang', 'toan_quoc', 460, 28, 20, 44),
('vn-sang-05', 'mon_nhanh_sang', 'toan_quoc', 220, 16, 15, 6),
('vn-sang-06', 'mon_nhanh_sang', 'toan_quoc', 210, 22, 6, 19),
('vn-lau-01', 'mon_lau_tiec', 'bac', 560, 48, 26, 34),
('vn-lau-02', 'mon_lau_tiec', 'nam', 490, 42, 22, 30),
('vn-lau-03', 'mon_lau_tiec', 'toan_quoc', 430, 46, 12, 34),
('vn-lau-04', 'mon_lau_tiec', 'toan_quoc', 410, 38, 14, 32),
('vn-lau-05', 'mon_lau_tiec', 'nam', 340, 35, 12, 22),
('gl-01', NULL, NULL, 380, 12, 8, 65),
('gl-02', NULL, NULL, 320, 22, 16, 14),
('gl-03', NULL, NULL, 230, 14, 16, 8),
('gl-04', NULL, NULL, 480, 32, 14, 55),
('gl-05', NULL, NULL, 420, 16, 14, 58),
('gl-06', NULL, NULL, 440, 28, 22, 32),
('gl-07', NULL, NULL, 360, 14, 10, 54),
('gl-08', NULL, NULL, 410, 12, 8, 72),
('gl-09', NULL, NULL, 140, 15, 7, 3),
('gl-10', NULL, NULL, 460, 36, 28, 16),
('gl-11', NULL, NULL, 510, 32, 14, 64),
('gl-12', NULL, NULL, 230, 14, 16, 8)
ON CONFLICT(recipe_id) DO UPDATE SET
  category = excluded.category,
  region = excluded.region,
  legacy_calories = excluded.legacy_calories,
  legacy_protein_g = excluded.legacy_protein_g,
  legacy_fat_g = excluded.legacy_fat_g,
  legacy_carb_g = excluded.legacy_carb_g;
